# Generated by Django 5.2.2 on 2025-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('user', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
